config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#overview'
  devise_scope :user do
    get 'login' => 'devise/sessions#new'
    get 'signup' => 'devise/registrations#new'
  end    
  
  post 'tipp_abgeben' => 'welcome#tipp_abgeben'
  get 'tipp/:id' => 'tipp#edit', as: :tipp_edit
  post 'tipp/:id' => 'tipp#update', as: :update_tipp
  get 'admin' => 'admin#gameresults'
  post 'goals_one/:id' => 'admin#add_goal_to_team_one', as: :goals_one
  post 'goals_two/:id' => 'admin#add_goal_to_team_two', as: :goals_two
  post 'remove_goals_one/:id' => 'admin#remove_goal_for_team_one', as: :remove_goals_one
  post 'remove_goals_two/:id' => 'admin#remove_goal_for_team_two', as: :remove_goals_two
  post 'finish/:id' => 'admin#end_game', as: :save_results
  post 'runde/:id' => 'admin#settings_update', as: :settings
  
  get 'user_lookup' => 'welcome#search'
  get 'groups' => 'welcome#groups'
  get 'games' => 'welcome#games'
  get 'tabelle' => 'welcome#tabelle'
  get 'iframe/turnierbaum' => 'welcome#turnierbaum'
  get 'turnierbaum' => 'welcome#turnierbaumview'
  get 'how-to-play' => 'welcome#how_to_play'
  get 'impressum' => 'welcome#impressum'
  get 'datenschutz' => 'welcome#datenschutz'
  get 'richtlinien' => 'welcome#richtlinien'
  get 'willkommen' => 'welcome#index'
  get 'problem_melden' => 'welcome#problem_melden'

end

app/views/admin/gameresults.html.erb
<div class="row">
  <div class="col-md-8">
    <% @games.each do |game| %> 
      <div class="game_container">
        <%= image_tag('flags/' + game.team_one.flag_url + '.png', :alt => game.team_one.country, :class => 'flag', :size => '32x32', :style => 'display: inline') %>  
        <span class="team"><%= game.team_one.shortname %></span>
            <%= form_for(game, url: save_results_url(game.id), method: :post) do |f| %>
            <div class="tipp_outercontainer">
              <div class="tipp_container">
                <%= f.text_field :goals_team_one, placeholder: "0", class: "tipp_goal", :required => true %>
                <span>:</span>
                <%= f.text_field :goals_team_two, placeholder: "0", class: "tipp_goal", :required => true %>
              </div>
              <%= f.submit "speichern", class: "tipp_submit"%>
              </div>
            <% end %>
        <span class="team"><%= game.team_two.shortname %></span>
        <%= image_tag('flags/' + game.team_two.flag_url + '.png', :alt => game.team_two.country, :class => 'flag', :size => '32x32') %>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <h2>Runde bearbeiten</h2>
    <p><strong>Aktuelle Runde: <%= @settings.status %></strong><br/>
      <strong>Hinweis:</strong>
      Die in der Auswahl angezeigte Runde ist immer die Gruppenphase und nicht die aktuelle Runde. Vor abspeichern einer neuen Runde müssen alle Spiele zuvor erfolgter Runden abgeschlossen sein und nach der Gruppenphase die Gruppentabellen mit den Tabellen der FIFA abgeglichen sein. Sollten Probleme auftretten bitte an JH oder LD wenden. Erst nach abgleich und überprüfen die neue Runde speichern. Runden nur einmal speichern, da sonst Dupplikate erstellt werden.<br/>
    <br/> Nach dem abpeichern einer Runde die erstellten Spiele mit den reellen Partien vergleichen.
    </p>
    <%= form_for(@settings, url: settings_url(1), method: :post) do |f| %>
      <div class="form-group">
        <%= select_tag :status, "<option>Gruppenphase</option><option>Achtelfinale</option><option>Viertelfinale</option><option>Halbfinale</option><option>Finale 3. und 4. Platz</option><option>Finale</option>".html_safe, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit "Speichern", class: "btn btn-default"%>
      </div>
    <% end %>
  </div>
</div>