config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#overview'
  devise_scope :user do
    get 'login' => 'devise/sessions#new'
    get 'signup' => 'devise/registrations#new'
  end    
  
  post 'tipp_abgeben' => 'welcome#tipp_abgeben'
  get 'tipp/:id' => 'tipp#edit', as: :tipp_edit
  post 'tipp/:id' => 'tipp#update', as: :update_tipp
  get 'admin' => 'admin#gameresults'
  post 'goals_one/:id' => 'admin#add_goal_to_team_one', as: :goals_one
  post 'goals_two/:id' => 'admin#add_goal_to_team_two', as: :goals_two
  post 'remove_goals_one/:id' => 'admin#remove_goal_for_team_one', as: :remove_goals_one
  post 'remove_goals_two/:id' => 'admin#remove_goal_for_team_two', as: :remove_goals_two
  post 'finish/:id' => 'admin#end_game', as: :save_results
  post 'runde/:id' => 'admin#settings_update', as: :settings
  
  get 'user_lookup' => 'welcome#search'
  get 'groups' => 'welcome#groups'
  get 'games' => 'welcome#games'
  get 'tabelle' => 'welcome#tabelle'
  get 'iframe/turnierbaum' => 'welcome#turnierbaum'
  get 'turnierbaum' => 'welcome#turnierbaumview'
  get 'how-to-play' => 'welcome#how_to_play'
  get 'impressum' => 'welcome#impressum'
  get 'datenschutz' => 'welcome#datenschutz'
  get 'richtlinien' => 'welcome#richtlinien'
  get 'willkommen' => 'welcome#index'
  get 'problem_melden' => 'welcome#problem_melden'

end

app/views/shared/_alle_spiele.html.erb
<% @all_games.each do |game| %> 
      <h5 class="time_date"><%= game.gametime.strftime("%d.%m um %H:%M") %> in <%= game.stadium.city %></h5>
      <div class="game_container">
        <%= image_tag('flags/' + game.team_one.flag_url + '.png', :alt => game.team_one.country, :class => 'flag', :size => '32x32', :style => 'display: inline') %>  
        <span class="team"><%= game.team_one.shortname %></span>
        <% if game.status === 'beendet' %>  
        <span class="game_ergebnis"><%= game.goals_team_one %> : <%= game.goals_team_two %></span>
        <% elsif game.status === 'gestartet' %>
          <span class="game_during">- : -</span>
        <% elsif @tipps.find_by_game_id(game.id) %>
          <span class="game_before">- : -</span>
        <% else %>
          <% if user_signed_in? && game.status != 'beendet' && game.status != 'gestartet' && !@tipps.find_by_game_id(game.id) %>
            <%= form_for(@tipp, :html => {class: "game_tipp", role: "form"}, url: tipp_abgeben_path) do |f| %>
            <%= f.hidden_field :game_id, value: game.id %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <div class="tipp_outercontainer">
              <div class="tipp_container">
                <%= f.text_field :goals_one, placeholder: "0", class: "tipp_goal", :required => true, :maxlength => 1 %>
                <span style="padding: 0px 3px 0px 3px">:</span>
                <%= f.text_field :goals_two, placeholder: "0", class: "tipp_goal", :required => true, :maxlength => 1 %>
              </div>
              <%= f.submit "Tippen", class: "tipp_submit"%>
            </div>
          <% end %>
          <% end %>
        <% end %>
        <span class="team"><%= game.team_two.shortname %></span>
        <%= image_tag('flags/' + game.team_two.flag_url + '.png', :alt => game.team_two.country, :class => 'flag', :size => '32x32') %>
      </div>
      <% if @tipps.find_by_game_id(game.id) %>
      <div class="tipp_bottom">
        <p> Ihr Tipp: <%= @tipps.find_by_game_id(game.id).goals_one %> : <%= @tipps.find_by_game_id(game.id).goals_two %> 
          <% if game != 'gestartet' && game != 'beendet' %>
            <a href="/tipp/<%= @tipps.find_by_game_id(game.id).id %>">Tipp bearbeiten</a>
          <% end %>
        </p>
      </div>
    <% end%>
<% end %>

app/views/shared/_explainer_homescreen.html.erb
<div class="visible-xs visible-sm">
  <!-- Large modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg" style="margin: 10px auto 20px auto; width: 100%;">Tippspiel auf Ihrem Homescreen</button>

  <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header"> <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button> <h4 class="modal-title" id="myLargeModalLabel">Tippspiel auf den Homescreen</h4> </div>
        <div class="modal-body">

          <!-- Nav tabs -->
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#iphone" aria-controls="iphone" role="tab" data-toggle="tab">iPhone</a></li>
            <li role="presentation"><a href="#android" aria-controls="android" role="tab" data-toggle="tab">Android</a></li>
          </ul>

          <!-- Tab panes -->
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="iphone">
              <h4><strong>Schritt 1:</strong><br/>Drücken Sie in der Fußzeile ihres mobilen Browsers das <%= render 'shared/svg/share_ios' %>-Symbol</h4>
              <h4><strong>Schritt 2:</strong><br/>Wählen Sie nun aus dem untersten Menü den zum Homescreen hinzufügen Button</h4>
              <%= image_tag('homescreen.jpg', :alt => 'Homescreen Explainer iOS', :style => 'width: 100%') %>
              <h4><strong>Schritt 3:</strong><br/>Titel nach belieben anpassen und hinzufügen drücken</h4>
            </div>
            <div role="tabpanel" class="tab-pane" id="android">
              <h4><strong>Schritt 1:</strong><br/>Suchen sie in ihrem Browser das <%= render 'shared/svg/settings_android' %> -Symbol</h4>
              <h4><strong>Schritt 2:</strong><br/>Wählen Sie nun aus den Menü den zum Startbildschirm hinzufügen Button</h4>
              <h4><strong>Schritt 3:</strong><br/>Titel nach belieben anpassen und hinzufügen drücken</h4>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_explainer_points.html.erb
<div>
  <h2 class="group_header">Punktesystem</h2>
  <table class="table table-hover">
      <p>
        Am Beispiel: <strong>Deutschland - Mexiko 3:1</strong>
      </p>
      <tbody>
        <tr>
          <td><strong>Richtiges Ergebnis</strong> (Bsp: 3:1)</td>
          <td style="text-align: right;">5 Punkte</td>
        </tr>
        <tr>
          <td><strong>Richtige Tordifferenz</strong> (Bsp: 2:0)</td>
          <td style="text-align: right;">3 Punkte</td>
        </tr>
        <tr>
          <td><strong>Richtige Tendenz</strong> (Bsp: 3:0)</td>
          <td style="text-align: right;">1 Punkte</td>
        </tr>

        <tr>
          <td><strong>Falscher Tipp</strong> (Bsp: 0:2)</td>
          <td style="text-align: right;">0 Punkte</td>
        </tr>
      </tbody>
  </table>
</div>

app/views/shared/_favicons.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#8f2684">
<meta name="msapplication-TileColor" content="#8f2684">
<meta name="theme-color" content="#8f2684">

app/views/shared/_groups.html.erb
<div>
    <table class="table table-hover" style="margin-bottom: 0px">
      <thead>
        <td class="col-md-1">Pos</td>
        <td class="col-md-5">Land</td>
        <td class="col-md-1 hidden-xs" style="text-align: center;">Spiele</td>
        <td class="col-md-1 visible-xs" style="text-align: center;">Sp</td>
        <td class=" hidden-xxs" style="text-align: center;">G U V</td>
        <td class="col-md-1 hidden-xxs" style="text-align: center;">Tore</td>
        <td class="col-md-1" style="text-align: right;">Pkt.</td>
      </thead>
      <tbody>
        <% group.teams.order('place asc').each do |team| %>
          <tr class="group_table">
            <td class="col-md-1"><%= team.place %></td>
            <td class="col-md-5 country"><%= image_tag('flags/' + team.flag_url + '.png', :alt => team.country, :class => 'flag', :size => '32x32', :style => 'margin-right: 10px;') %> <%= team.country %></td>
            <td class="shortname"><%= image_tag('flags/' + team.flag_url + '.png', :alt => team.country, :class => 'flag', :size => '32x32', :style => 'margin-right: 10px;') %> <%= team.shortname %></td>
            <td class="col-md-1" style="text-align: center;"><%= team.games %></td>
            <td class="hidden-xxs" style="text-align: center;"><%= team.wins %> <%= team.draws %> <%= team.losses %></td>
            <td class="col-md-1 hidden-xxs" style="text-align: center;"><%= team.goals %>:<%= team.goals_allowed %></td>
            <td class="col-md-1" style="text-align: right;"><%= team.points %></td>
          </tr>
       <% end %>
    </tbody>  
  </table>
</div>

app/views/shared/_live.html.erb
<% if !@live_games.empty? %>
<h2>Derzeit Live</h2>
<% @live_games.each do |game| %> 
  <h5 class="time_date"><%= game.gametime.strftime("%d.%m um %H:%M") %> in <%= game.stadium.city %></h5>
  <div class="game_container">
    <%= image_tag('flags/' + game.team_one.flag_url + '.png', :alt => game.team_one.country, :class => 'flag', :size => '32x32', :style => 'display: inline') %>  
    <span class="team"><%= game.team_one.shortname %></span>
      <span class="game_during">- : -</span>
    <span class="team"><%= game.team_two.shortname %></span>
    <%= image_tag('flags/' + game.team_two.flag_url + '.png', :alt => game.team_two.country, :class => 'flag', :size => '32x32') %>
  </div>
  <% if @tipps.find_by_game_id(game.id) %>
  <div class="tipp_bottom">
    <p> Ihr Tipp: <%= @tipps.find_by_game_id(game.id).goals_one %> : <%= @tipps.find_by_game_id(game.id).goals_two %> 
    </p>
</div>
  <% end %>
  <% end %>
  <% end %>

app/views/shared/_recently_finished.html.erb
<% if @recently_finished_games.any? && user_signed_in? %>
<% @recently_finished_games.each do |game| %> 
  <h5 class="time_date"><%= game.gametime.strftime("%d.%m um %H:%M") %> in <%= game.stadium.city %></h5>
  <div class="game_container">
    <%= image_tag('flags/' + game.team_one.flag_url + '.png', :alt => game.team_one.country, :class => 'flag', :size => '32x32', :style => 'display: inline') %>  
    <span class="team"><%= game.team_one.shortname %></span>
    <% if game.status === 'beendet' %>  
    <span class="game_ergebnis"><%= game.goals_team_one %> : <%= game.goals_team_two %></span>
    <% elsif game.status === 'gestartet' %>
      <span class="game_during">- : -</span>
    <% elsif @tipps.find_by_game_id(game.id) %>
      <span class="game_before">- : -</span>
    <% else %>
      <% if user_signed_in? && !@tipps.find_by_game_id(game.id) %>
        <%= form_for(@tipp, :html => {class: "game_tipp", role: "form"}, url: tipp_abgeben_path) do |f| %>
        <%= f.hidden_field :game_id, value: game.id %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="tipp_outercontainer">
          <div class="tipp_container">
            <%= f.text_field :goals_one, placeholder: "0", class: "tipp_goal" %>
            <span>:</span>
            <%= f.text_field :goals_two, placeholder: "0", class: "tipp_goal" %>
          </div>
          <%= f.submit "Tippen", class: "tipp_submit"%>
        </div>
      <% end %>
      <% end %>
    <% end %>
    <span class="team"><%= game.team_two.shortname %></span>
    <%= image_tag('flags/' + game.team_two.flag_url + '.png', :alt => game.team_two.country, :class => 'flag', :size => '32x32') %>
  </div>
  <% if @tipps.find_by_game_id(game.id) %>
  <div class="tipp_bottom">
    <p> Ihr Tipp: <%= @tipps.find_by_game_id(game.id).goals_one %> : <%= @tipps.find_by_game_id(game.id).goals_two %> 
      <span style="color: green"> - <%= @tipps.find_by_game_id(game.id).points %> Punkt<%= 'e' unless @tipps.find_by_game_id(game.id).points === 1 %></span>
    </p>
  </div>
  <% end%>
  <% end %>
  <% end %>

app/views/shared/_result.html.erb
<div class="col-md-12" style="display: inline-block;">
  <% if params[:action] == 'search' %>
  <%= bootstrap_flash %>
  <% end %>
</div>
<% if @search %>
<div>
<table class="table table-hover">
    <thead>
      <td>Pos</td>
      <td>Nutzer</td>
      <td style="text-align: right;">Punkte</td>
    </thead>
    <tbody>
      <tr class="user_table">
          <td class="col-md-1"><%= @search.position %></td>
          <td class="col-md-8"><%= @search.nickname %></td>
          <td class="col-md-3" style="text-align: right;"><%= @search.points %></td>
        </tr>
    </tbody>  
  </table>
</div>
<% end %>

app/views/shared/_result.js.erb
$('#results').html("<%= j (render 'shared/result.html') %>")

app/views/shared/_tabelle.html.erb
<% if user_signed_in? %>
<div style="margin-bottom: 20px;">
  <h2 class="group_header"><% if current_page?(action: 'tabelle') %>Tipp Tabelle<% else %>Top 5<% end %></h2>
  <table class="table table-hover">
    <thead>
      <td>Pos</td>
      <td>Nutzer</td>
      <td style="text-align: right;">Punkte</td>
    </thead>
    <tbody>
      <% @user.each do |user| %>
      <tr class="user_table" <% if user === current_user %>style="font-weight: 500;"<% end %>>
          <td class="col-md-1"><%= user.position %></td>
          <td class="col-md-8"><%= user.nickname %></td>
          <td class="col-md-3" style="text-align: right;"><%= user.points %></td>
        </tr>
      <% end %>
      <% if !@user.include?(current_user.id) && !current_page?(action: 'tabelle') %>
      <tr class="user_table" style="font-weight: 500;">
        <td class="col-md-1"></td>
        <td class="col-md-8">...</td>
        <td class="col-md-3" style="text-align: right;"></td>
      </tr>
      <tr class="user_table" style="font-weight: 500;">
        <td class="col-md-1"><%= current_user.position %></td>
        <td class="col-md-8"><%= current_user.nickname %></td>
        <td class="col-md-3" style="text-align: right;"><%= current_user.points %></td>
      </tr>
      <% end %>
    </tbody>  
  </table>
    <% if !current_page?(action: 'tabelle') %>
      <%= link_to 'Komplette Tipp-Tabelle anzeigen', tabelle_path %>
    <% else %>
      <%= will_paginate @user, renderer: BootstrapPagination::Rails %>
    <% end %>
</div>
<% end %>

app/views/shared/_turnierbaum_game.html.erb
<% if Game.find(gamenr) %>
<% Game.where('id = ?', gamenr).each do |game|%>
<div class="game_container">
  <%= image_tag('flags/' + game.team_one.flag_url + '.png', :alt => game.team_one.country, :class => 'flag', :size => '32x32', :style => 'display: inline') %>  
  <span class="team"><%= game.team_one.shortname %></span>
  <% if game.status === 'beendet' %>  
  <span class="game_ergebnis"><%= game.goals_team_one %> : <%= game.goals_team_two %></span>
  <% else %>
    <span class="game_before">- : -</span>
  <% end %>
  <span class="team"><%= game.team_two.shortname %></span>
  <%= image_tag('flags/' + game.team_two.flag_url + '.png', :alt => game.team_two.country, :class => 'flag', :size => '32x32') %>
</div>
<% end %>
<% else %>
<div class="game_container">
  <!--<%= image_tag('flags/' + '26bd' + '.png', :class => 'flag', :size => '32x32', :style => 'display: inline') %>  -->
  <span class="team"><%= teamone %></span>
    <span class="game_before">- : -</span>
  <span class="team"><%= teamtwo %></span>
  <!--  <%= image_tag('flags/' + '26bd' + '.png', :class => 'flag', :size => '32x32', :style => 'display: inline') %>  -->
</div>
<% end %>

app/views/shared/_turnierbaum_game2.html.erb
<% if Game.where('id = ?', gamenr).any? %>
<% Game.where('id = ?', gamenr).each do |game|%>
<h5 class="time_date">Spiel <%= gamenr %> <%= game.gametime.strftime("%d.%m um %H:%M") %> in <%= game.stadium.city %></h5>
<div class="game_container">
  <%= image_tag('flags/' + game.team_one.flag_url + '.png', :alt => game.team_one.country, :class => 'flag', :size => '32x32', :style => 'display: inline') %>  
  <span class="team"><%= game.team_one.shortname %></span>
  <% if game.status === 'beendet' %>  
  <span class="game_ergebnis"><%= game.goals_team_one %> : <%= game.goals_team_two %></span>
  <% else %>
    <span class="game_before">- : -</span>
  <% end %>
  <span class="team"><%= game.team_two.shortname %></span>
  <%= image_tag('flags/' + game.team_two.flag_url + '.png', :alt => game.team_two.country, :class => 'flag', :size => '32x32') %>
</div>
<% end %>
<% else %>
<div class="game_container">
  <!--<%= image_tag('flags/' + '26bd' + '.png', :class => 'flag', :size => '32x32', :style => 'display: inline') %>  -->
  <span class="team"><%= teamone %></span>
    <span class="game_before">- : -</span>
  <span class="team"><%= teamtwo %></span>
  <!--  <%= image_tag('flags/' + '26bd' + '.png', :class => 'flag', :size => '32x32', :style => 'display: inline') %>  -->
</div>
<% end %>

app/views/shared/_twitter.html.erb
<a id="twitter" class="twitter-timeline" data-lang="de" data-height="100VH" data-theme="light" href="https://twitter.com/fifaworldcup_de?ref_src=twsrc%5Etfw">Tweets by fifaworldcup_de</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

app/views/shared/_upcoming.html.erb
<% @upcoming_games.each do |game| %> 
      <h5 class="time_date"><%= game.gametime.strftime("%d.%m um %H:%M") %> in <%= game.stadium.city %></h5>
      <div class="game_container">
        <%= image_tag('flags/' + game.team_one.flag_url + '.png', :alt => game.team_one.country, :class => 'flag', :size => '32x32', :style => 'display: inline') %>  
        <span class="team"><%= game.team_one.shortname %></span>
        <% if game.status === 'beendet' %>  
        <span class="game_ergebnis"><%= game.goals_team_one %> : <%= game.goals_team_two %></span>
        <% elsif game.status === 'gestartet' %>
          <span class="game_during">- : -</span>
        <% elsif @tipps.find_by_game_id(game.id) %>
          <span class="game_before">- : -</span>
        <% else %>
          <% if user_signed_in? && game.status != 'beendet' && game.status != 'gestartet' && !@tipps.find_by_game_id(game.id) %>
            <%= form_for(@tipp, :html => {class: "game_tipp", role: "form"}, url: tipp_abgeben_path) do |f| %>
            <%= f.hidden_field :game_id, value: game.id %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <div class="tipp_outercontainer">
              <div class="tipp_container">
                <%= f.text_field :goals_one, placeholder: "0", class: "tipp_goal", :required => true, :maxlength => 1 %>
                <span style="padding: 0px 3px 0px 3px">:</span>
                <%= f.text_field :goals_two, placeholder: "0", class: "tipp_goal", :required => true, :maxlength => 1 %>
              </div>
              <%= f.submit "Tippen", class: "tipp_submit"%>
            </div>
          <% end %>
          <% end %>
        <% end %>
        <span class="team"><%= game.team_two.shortname %></span>
        <%= image_tag('flags/' + game.team_two.flag_url + '.png', :alt => game.team_two.country, :class => 'flag', :size => '32x32') %>
      </div>
      <% if @tipps.find_by_game_id(game.id) %>
      <div class="tipp_bottom">
        <p> Ihr Tipp: <%= @tipps.find_by_game_id(game.id).goals_one %> : <%= @tipps.find_by_game_id(game.id).goals_two %> 
          <% if game != 'gestartet' && game != 'beendet' %>
            <a href="/tipp/<%= @tipps.find_by_game_id(game.id).id %>">Tipp bearbeiten</a>
          <% end %>
        </p>
      </div>
    <% end%>
<% end %>