config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#overview'
  devise_scope :user do
    get 'login' => 'devise/sessions#new'
    get 'signup' => 'devise/registrations#new'
  end    
  
  post 'tipp_abgeben' => 'welcome#tipp_abgeben'
  get 'tipp/:id' => 'tipp#edit', as: :tipp_edit
  post 'tipp/:id' => 'tipp#update', as: :update_tipp
  get 'admin' => 'admin#gameresults'
  post 'goals_one/:id' => 'admin#add_goal_to_team_one', as: :goals_one
  post 'goals_two/:id' => 'admin#add_goal_to_team_two', as: :goals_two
  post 'remove_goals_one/:id' => 'admin#remove_goal_for_team_one', as: :remove_goals_one
  post 'remove_goals_two/:id' => 'admin#remove_goal_for_team_two', as: :remove_goals_two
  post 'finish/:id' => 'admin#end_game', as: :save_results
  post 'runde/:id' => 'admin#settings_update', as: :settings
  
  get 'user_lookup' => 'welcome#search'
  get 'groups' => 'welcome#groups'
  get 'games' => 'welcome#games'
  get 'tabelle' => 'welcome#tabelle'
  get 'iframe/turnierbaum' => 'welcome#turnierbaum'
  get 'turnierbaum' => 'welcome#turnierbaumview'
  get 'how-to-play' => 'welcome#how_to_play'
  get 'impressum' => 'welcome#impressum'
  get 'datenschutz' => 'welcome#datenschutz'
  get 'richtlinien' => 'welcome#richtlinien'
  get 'willkommen' => 'welcome#index'
  get 'problem_melden' => 'welcome#problem_melden'

end

app/models/tipp.rb
class Tipp < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :game
  validates_presence_of :goals_one, :goals_two, :user_id, :game_id
  validates_numericality_of :goals_one, :goals_two
  
  def points
    game_goals_one = self.game.goals_team_one
    game_goals_two = self.game.goals_team_two
    goals_one = self.goals_one
    goals_two = self.goals_two
    # Nichts richtig
    points_tipp = 0
    #Tendenz und Tore richtig
    return points_tipp += 5 if game_goals_one == goals_one && game_goals_two == goals_two
    # Tendenz und Torverhältnis richtig
    return points_tipp += 3 if ((game_goals_one > game_goals_two && goals_one > goals_two) ||
                           (game_goals_one === game_goals_two && goals_one === goals_two) ||
                           (game_goals_one < game_goals_two && goals_one < goals_two)) &&
                           (game_goals_one - game_goals_two == goals_one - goals_two)
    # Nur Tendenz richtig
    return points_tipp += 1 if ((game_goals_one > game_goals_two && goals_one > goals_two) ||
                           (game_goals_one < game_goals_two && goals_one < goals_two))
    points_tipp
  end
  
  
end

app/controllers/tipp_controller.rb
class TippController < ApplicationController
  
  def edit
    @tipp = Tipp.find(params[:id])
    @game = @tipp.game
    if @game.status === 'gestartet' || @game.status === 'beendet' || @tipp.user.id != current_user.id    
      redirect_to root_path
    end
  end
  
  def update
    @tipp = Tipp.find(params[:id])
    @game = @tipp.game
    if @tipp.update(tipp_params)
      flash[:success] = "Tipp erfolgreich bearbeitet"
      redirect_to root_path
    else
      flash[:warning] = "Ein Fehler ist aufgetreten"
      render 'edit'
    end
  end

  
private
  
  def tipp_params
    params.require(:tipp).permit(:user_id, :game_id, :goals_one, :goals_two)
  end
    
end

app/views/tipp/edit.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="game_container">
      <%= image_tag('flags/' + @game.team_one.flag_url + '.png', :alt => @game.team_one.country, :class => 'flag', :size => '32x32', :style => 'display: inline') %>  
      <span class="team"><%= @game.team_one.shortname %></span>
      <%= form_for(@tipp, url: update_tipp_url, method: :post) do |f| %>
      <div class="tipp_outercontainer">
        <div class="tipp_container">
          <%= f.text_field :goals_one, class: "tipp_goal", placeholder: "0" %>
          <span>:</span>
          <%= f.text_field :goals_two, class: "tipp_goal", placeholder: "0" %>
          </div>
          <%= f.submit "speichern", class: "tipp_submit"%>
      </div>
      <% end %>
      <span class="team"><%= @game.team_two.shortname %></span>
      <%= image_tag('flags/' + @game.team_two.flag_url + '.png', :alt => @game.team_two.country, :class => 'flag', :size => '32x32') %>
    </div>
  </div>
</div>