config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#overview'
  devise_scope :user do
    get 'login' => 'devise/sessions#new'
    get 'signup' => 'devise/registrations#new'
  end    
  
  post 'tipp_abgeben' => 'welcome#tipp_abgeben'
  get 'tipp/:id' => 'tipp#edit', as: :tipp_edit
  post 'tipp/:id' => 'tipp#update', as: :update_tipp
  get 'admin' => 'admin#gameresults'
  post 'goals_one/:id' => 'admin#add_goal_to_team_one', as: :goals_one
  post 'goals_two/:id' => 'admin#add_goal_to_team_two', as: :goals_two
  post 'remove_goals_one/:id' => 'admin#remove_goal_for_team_one', as: :remove_goals_one
  post 'remove_goals_two/:id' => 'admin#remove_goal_for_team_two', as: :remove_goals_two
  post 'finish/:id' => 'admin#end_game', as: :save_results
  post 'runde/:id' => 'admin#settings_update', as: :settings
  
  get 'user_lookup' => 'welcome#search'
  get 'groups' => 'welcome#groups'
  get 'games' => 'welcome#games'
  get 'tabelle' => 'welcome#tabelle'
  get 'iframe/turnierbaum' => 'welcome#turnierbaum'
  get 'turnierbaum' => 'welcome#turnierbaumview'
  get 'how-to-play' => 'welcome#how_to_play'
  get 'impressum' => 'welcome#impressum'
  get 'datenschutz' => 'welcome#datenschutz'
  get 'richtlinien' => 'welcome#richtlinien'
  get 'willkommen' => 'welcome#index'
  get 'problem_melden' => 'welcome#problem_melden'

end

app/views/layouts/application.html.erb
<% if !@scale %>
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <% if !@scale %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <% else %>
    <meta name="viewport" content="width=1200" >
    <% end %>
    <meta name="format-detection" content="telephone=no"/>
    <meta name="msapplication-tap-highlight" content="no"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <!-- COMMON TAGS -->
    <meta charset="utf-8">
    <title>KEK WM Tippspiel 2018</title>
    <!-- Search Engine -->
    <meta name="description" content="Das Tippspiel für die WM 2018 von KEK Anwendungssysteme GmbH. Mitspielen und 500€ für eine wohltätige Organisation Ihrer Wahl gewinnen.">
    <meta name="image" content="https://www.kek-tipp.de/og/kek_tipp_og.jpg">
    <!-- Schema.org for Google -->
    <meta itemprop="name" content="KEK WM Tippspiel 2018">
    <meta itemprop="description" content="Das Tippspiel für die WM 2018 von KEK Anwendungssysteme GmbH. Mitspielen und 500€ für eine wohltätige Organisation Ihrer Wahl gewinnen.">
    <meta itemprop="image" content="https://www.kek-tipp.de/og/kek_tipp_og.jpg">
    <!-- Open Graph general (Facebook, Pinterest & Google+) -->
    <meta property="og:title" content="KEK WM Tippspiel 2018">
    <meta property="og:description" content="Das Tippspiel für die WM 2018 von KEK Anwendungssysteme GmbH. Mitspielen und 500€ für eine wohltätige Organisation Ihrer Wahl gewinnen.">
    <meta property="og:image" content="https://www.kek-tipp.de/og/kek_tipp_og.jpg"/>
    <meta property='og:image' content='https://www.kek-tipp.de/og/kek_tipp_og.jpg'/>
    <meta property="og:url" content="https://www.kek-tipp.de/">
    <meta property="og:site_name" content="KEK Tippspiel">
    <meta property="og:locale" content="de">
    <meta property="og:type" content="website">
    <title><%= content_for?(:title) ? yield(:title) : "KEK Tippspiel" %></title>
    <%= csrf_meta_tags %>
    <%= render 'shared/favicons' %>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600|Orbitron:400,700" rel="stylesheet">
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-TZ95235');</script>
    <!-- End Google Tag Manager -->
  </head>
  <body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TZ95235"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <!--[if !IE]>
    <div id="preloader" class="preloader">
      <div class="lds-css ng-scope">
        <div style="width:100%;height:100%" class="lds-ball">
          <div></div>
        </div>
      </div>
    </div>
    <![endif]-->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">
          <%= image_tag 'KEK-Tippspiel.png', :alt => "WM Tippspiel KEK Anwendungssysteme GmbH", :class => 'logo', height: '30px' %>
        </a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to "Spiele", "/"  %></li>
              <li><%= link_to "Turnierbaum", "/turnierbaum"  %></li>
              <li><%= link_to "Tipp-Tabelle", "/tabelle" %></li>
            <% end %>
            <li><%= link_to "Anleitung", "/how-to-play" %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <% if current_user.role_name === 'admin' %>
            <li><%= link_to "Admin", admin_path %></li>
            <% end %>
            <li><%= link_to "Ausloggen", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Anmelden", login_path %></li>
            <li><%= link_to "Registrieren", signup_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container" style="margin-top: 70px;">
          <%= bootstrap_flash %>
          <%= yield %>

      <footer>
        <p>
          &copy; 2018 <%= link_to "KEK Anwendungssysteme GmbH", "http://www.kek-it.de", target: "_blank" %>   |   
          <%= link_to "Datenschutz", datenschutz_path, target: "_blank" %>   |   
          <%= link_to "Impressum", impressum_path, target: "_blank" %>   |   
          <%= link_to "Nutzungsrichtlinien", richtlinien_path, target: "_blank" %>   |   Emoji artwork provided by 
          <%= link_to "EmojiOne", "http://emojione.com" %>   |   
          <%= link_to "Problem melden", problem_melden_path %>
        </p>
      </footer>

    </div> <!-- /container -->
    <script type="text/javascript">
      element = document.getElementById("preloader");
      element.remove();
    </script>  
  </body>
</html>
<% else %>
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"> 
    <meta name="viewport" content="width=1200, initial-scale=1.0" >
    <title><%= content_for?(:title) ? yield(:title) : "KEK Tippspiel" %></title>
    <%= csrf_meta_tags %>
    <%= render 'shared/favicons' %>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600|Orbitron:400,700" rel="stylesheet">

  </head>
  <body>
          <%= yield %>
    <script type="text/javascript">
      element = document.getElementById("preloader");
      element.remove();
    </script>  
  </body>
</html>
<% end %>